# frozen_string_literal: true

pin '@popperjs/core', to: 'https://unpkg.com/@popperjs/core@2.11.2/dist/esm/index.js' # use unpkg.com as ga.jspm.io contains a broken popper package
pin 'bootstrap', to: 'https://ga.jspm.io/npm:bootstrap@5.3.3/dist/js/bootstrap.esm.js'
pin 'jquery', to: 'jquery-3.7.0.min.js'
pin 'bootstrap-multiselect', to: 'bootstrap-multiselect.min.js'
pin 'bootstrap-switch', to: 'bootstrap-switch.min.js'
pin 'fuzzysort', to: 'fuzzysort.js'
pin 'jquery.multi-select', to: 'jquery.multi-select.min.js'
pin 'bootstrap-markdown', to: 'bootstrap-markdown.js'
pin 'bootstrap-datepicker.min.js', to: 'bootstrap-datepicker.min.js'
pin 'bootstrap-switch', to: 'bootstrap-switch.min.js'
pin 'jquery.quicksearch', to: 'jquery.quicksearch.min.js'
pin 'forms', to: 'forms.js'
pin 'interfaces', to: 'interfaces.js'
pin 'tables', to: 'tables.js'
pin 'formula', to: 'forms/formula.js'
pin 'input-connected', to: 'forms/input-connected.js'
pin 'jquery.multi-select-extend', to: 'forms/jquery.multi-select-extend.js'
pin 'debounce', to: 'debounce.js'
pin 'controllers/combobox_controller', to: 'controllers/combobox_controller.js'
pin 'nested-dropdown', to: 'forms/nested-dropdown.js'
