pin "@popperjs/core", to: "https://unpkg.com/@popperjs/core@2", preload: true
pin "bootstrap", to: "bootstrap.min.js", preload: true
pin "jquery", to: "jquery-3.7.0.min.js", preload: true
pin "bootstrap-multiselect", to: "bootstrap-multiselect.min.js", preload: true
pin "jquery.multi-select", to: "jquery.multi-select.min.js", preload: true
pin "bootstrap-markdown", to: "bootstrap-markdown.js", preload: true
pin "bootstrap-datepicker.min.js", to: "bootstrap-datepicker.min.js", preload: true
pin "bootstrap-switch", to: "bootstrap-switch.min.js", preload: true
pin "jquery.quicksearch", to: "jquery.quicksearch.min.js", preload: true
